language: r
script: "./build.R"
sudo: required
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJCGFQEZ3CD243KHA
  secret_access_key:
    secure: JbE864GTKaPnVGRXv8MJGqFdizrFHoHJBl61Y/1noVDxKJKvhRnSCubHW1AtTVEzarHjj4dVT7yOIN7CN99mKgxYoPt7wXoxBKtwCC07l7Uimk/CdsrSxgx9vaWOht0aGaZdFl3dxj7UCmSPM5bnSEB/XJcQTv7X1EgXfnfOs5Q=
  bucket: kurtharriger-rmeetup
  local-dir: target
  upload-dir: rcdpres
  acl: public_read
  on:
    repo: kurtharriger/rcdpres
